// packages/angular/src/CyberSheetComponent.ts
/**
 * CyberSheetComponent.ts
 * 
 * Angular component for Cyber Sheet
 */

import {
  Component,
  ElementRef,
  Input,
  OnInit,
  OnDestroy,
  ViewChild,
  Output,
  EventEmitter
} from '@angular/core';
import { CommonModule } from '@angular/common';
import { CyberSheetService } from './internal';
import type { Worksheet, CollaborationEngine } from '@cyber-sheet/core';
import type { CanvasRenderer } from '@cyber-sheet/renderer-canvas';

@Component({
  selector: 'cyber-sheet',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div #container [ngStyle]="containerStyle"></div>
  `,
  styles: [`
    :host {
      display: block;
      position: relative;
      overflow: hidden;
    }
  `]
})
export class CyberSheetComponent implements OnInit, OnDestroy {
  @ViewChild('container', { static: true }) containerRef!: ElementRef<HTMLDivElement>;

  @Input() data?: any[][];
  @Input() enableFormulas = false;
  @Input() enableCollaboration = false;
  @Input() collaborationUrl?: string;
  @Input() width: number | string = '100%';
  @Input() height: number | string = 600;

  @Output() cellChange = new EventEmitter<{ row: number; col: number; value: any }>();
  @Output() selectionChange = new EventEmitter<{ start: { row: number; col: number }; end: { row: number; col: number } }>();

  worksheet: Worksheet | null = null;
  renderer: CanvasRenderer | null = null;
  collaboration: CollaborationEngine | null = null;

  private cellChangeHandler: EventListener | null = null;

  constructor(private cyberSheetService: CyberSheetService) {}

  get containerStyle() {
    return {
      width: typeof this.width === 'number' ? `${this.width}px` : this.width,
      height: typeof this.height === 'number' ? `${this.height}px` : this.height,
      position: 'relative',
      overflow: 'hidden'
    };
  }

  async ngOnInit() {
    const container = this.containerRef.nativeElement;

    const { worksheet, renderer, formulaEngine, collaboration } =
      await this.cyberSheetService.createRenderer(container, {
        data: this.data,
        enableFormulas: this.enableFormulas,
        enableCollaboration: this.enableCollaboration,
        collaborationUrl: this.collaborationUrl
      });

    this.worksheet = worksheet;
    this.renderer = renderer;
    this.collaboration = collaboration || null;

    // Handle cell changes
    this.cellChangeHandler = ((e: CustomEvent) => {
      const { row, col, value } = e.detail;
      this.cellChange.emit({ row, col, value });
    }) as EventListener;

    document.addEventListener('cyber-sheet-cell-change', this.cellChangeHandler);
  }

  ngOnDestroy() {
    this.collaboration?.disconnect();
    if (this.cellChangeHandler) {
      document.removeEventListener('cyber-sheet-cell-change', this.cellChangeHandler);
    }
  }

  setCell(row: number, col: number, value: any) {
    if (!this.worksheet) return;
    this.worksheet.setCellValue({ row, col }, value);
  }

  getCell(row: number, col: number) {
    if (!this.worksheet) return null;
    return this.worksheet.getCell({ row, col })?.value;
  }

  refresh() {
    if (this.renderer && this.containerRef) {
      this.containerRef.nativeElement.dispatchEvent(new CustomEvent('cyber-sheet-refresh'));
    }
  }
}

// packages/svelte/src/CyberSheet.svelte
<script lang="ts">
  import { onMount, onDestroy } from 'svelte';
  import { createCyberSheetStore, initializeCyberSheet, type CyberSheetState } from './cyberSheetStore';
  import type { Writable } from 'svelte/store';

  export let data: any[][] | undefined = undefined;
  export let enableFormulas = false;
  export let enableCollaboration = false;
  export let collaborationUrl: string | undefined = undefined;
  export let width: number | string = '100%';
  export let height: number | string = 600;
  export let className: string = '';
  export let style: Record<string, any> = {};
  export let onCellChange: ((row: number, col: number, value: any) => void) | undefined = undefined;
  export let onSelectionChange: ((selection: { start: { row: number; col: number }; end: { row: number; col: number } }) => void) | undefined = undefined;

  let containerRef: HTMLDivElement;
  let store: Writable<CyberSheetState> = createCyberSheetStore();
  let state: CyberSheetState;
  let cellChangeHandler: EventListener | null = null;

  $: state = $store;

  onMount(async () => {
    if (!containerRef) return;

    await initializeCyberSheet(containerRef, store, {
      data,
      enableFormulas,
      enableCollaboration,
      collaborationUrl
    });

    // Handle cell changes
    if (onCellChange) {
      cellChangeHandler = ((e: CustomEvent) => {
        const { row, col, value } = e.detail;
        onCellChange?.(row, col, value);
      }) as EventListener;

      document.addEventListener('cyber-sheet-cell-change', cellChangeHandler);
    }
  });

  onDestroy(() => {
    state?.collaboration?.disconnect();
    if (cellChangeHandler) {
      document.removeEventListener('cyber-sheet-cell-change', cellChangeHandler);
    }
  });

  export function setCell(row: number, col: number, value: any) {
    if (!state?.worksheet) return;
    state.worksheet.setCellValue({ row, col }, value);
  }

  export function getCell(row: number, col: number) {
    if (!state?.worksheet) return null;
    return state.worksheet.getCell({ row, col })?.value;
  }

  export function refresh() {
    if (state?.renderer && containerRef) {
      containerRef.dispatchEvent(new CustomEvent('cyber-sheet-refresh'));
    }
  }

  const computedStyle = {
    width: typeof width === 'number' ? `${width}px` : width,
    height: typeof height === 'number' ? `${height}px` : height,
    position: 'relative',
    overflow: 'hidden',
    ...style
  };
</script>

<div
  bind:this={containerRef}
  class={className}
  style={Object.entries(computedStyle).map(([k, v]) => `${k}: ${v}`).join('; ')}
/>
